name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish release ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          skip-unshallow: 'true'
          abbrev: false
          commit-ish: HEAD
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: 17
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Build project
        run: cd AndroidProject && ./gradlew assembleRelease

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{steps.tagger.outputs.tag}}
          generate_release_notes: true
          prerelease: false
          name: ${{steps.tagger.outputs.tag}}
          files: |
            ./AndroidProject/app/build/outputs/apk/release/*-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
